<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    /**
     * Run the migrations.
     */

    public function up(): void
    {
        Schema::create('lead_search_leads', function (Blueprint $table) {
            $table->id();
            $table->bigInteger('ProspectAutoId')->nullable();
            $table->uuid('ProspectID')->nullable();
            $table->uuid('OwnerId')->nullable();
            $table->boolean('IsLead')->nullable();
            $table->boolean('IsStarredLead')->nullable();
            $table->boolean('IsTaggedLead')->nullable();
            $table->boolean('CanUpdate')->nullable();
            $table->string('NotableEvent')->nullable();
             $table->text('ProspectActivityId_Max')->nullable();
            $table->text('ProspectActivityId_Min')->nullable();
            $table->timestamp('NotableEventdate')->nullable();
            $table->string('ProspectActivityName_Max')->nullable();
            $table->timestamp('ProspectActivityDate_Max')->nullable();
            $table->timestamp('LeadLastModifiedOn')->nullable();
            $table->string('FirstName')->nullable();
            $table->string('LastName')->nullable();
            $table->string('EmailAddress')->nullable();
            $table->string('Phone')->nullable();
            $table->string('SourceCampaign')->nullable();
            $table->string('SourceMedium')->nullable();
            $table->string('SourceContent')->nullable();
            $table->string('Score')->nullable();
            $table->string('StatusReason')->nullable();
            $table->string('DeletionStatusCode')->nullable();
            $table->uuid('RelatedProspectId')->nullable();
            $table->string('Web_Referrer')->nullable();
            $table->string('Web_RefKeyword')->nullable();
            $table->json('raw')->nullable();
            $table->string('ProspectStage')->nullable();
            $table->string('CreatedByName')->nullable();
            $table->timestamp('CreatedOn')->nullable();
            $table->timestamp('LeadConversionDate')->nullable();
            $table->string('ModifiedBy')->nullable();
            $table->string('ModifiedByName')->nullable();
            $table->string('mx_Lead_URL')->nullable();
            $table->string('mx_City')->nullable();
            $table->string('mx_Country')->nullable();
            $table->string('OwnerIdName')->nullable();
            $table->string('OwnerIdEmailAddress')->nullable();
            $table->string('Origin')->nullable();
            $table->string('mx_Course_Interested')->nullable();
            $table->string('mx_Lead_Course')->nullable();
            $table->string('mx_Ad_Name')->nullable();
            $table->string('mx_campaign_Id')->nullable();
            $table->string('mx_Adset_Name')->nullable();
            $table->string('mx_UTM_Source')->nullable();
            $table->string('mx_UTM_Term')->nullable();
            $table->string('mx_Facebook_Form')->nullable();
            $table->string('mx_Facebook_Page')->nullable();
            $table->string('mx_Status')->nullable();
            $table->string('mx_Outcome')->nullable();
            $table->string('mx_GCLID')->nullable();
            $table->string('mx_Primary_reason_for_course')->nullable();
            $table->string('mx_utm_creative_id')->nullable();
            $table->string('mx_FB_LeadGen_ID')->nullable();
            $table->string('mx_Program_Type')->nullable();
            $table->string('mx_Source_Category')->nullable();
            $table->string('mx_Courses_Category')->nullable();
            $table->string('Notes')->nullable();
            $table->string('mx_Total_Calls_in_Lead')->nullable();
            $table->string('mx_Total_Answered_Calls')->nullable();
            $table->timestamp('mx_Last_Follow_Up_Date')->nullable();
            $table->string('mx_Pre_Qualified_Leads')->nullable();
            $table->string('mx_Activity_Notes')->nullable();
            $table->string('mx_utm_medium')->nullable();
            $table->string('LeadAge')->nullable();
            $table->string('mx_Education_Completed')->nullable();
            $table->string('mx_QualityScore01')->nullable();
            $table->string('mx_Quality_Lead')->nullable();
            $table->string('mx_AD_Network')->nullable();
            $table->timestamp('LastVisitDate')->nullable();
            $table->timestamps();
        });
    }

    // public function up(): void
    // {
    //     Schema::create('lead_search_leads', function (Blueprint $table) {
    //         $table->id();
    //         $table->uuid('ProspectID')->nullable();
    //         $table->bigInteger('ProspectAutoId')->nullable();
    //         $table->text('ProspectActivityId_Max')->nullable();
    //         $table->text('ProspectActivityId_Min')->nullable();
    //         $table->string('StatusCode')->nullable();
    //         $table->string('StatusReason')->nullable();
    //         $table->string('DeletionStatusCode')->nullable();
    //         $table->boolean('IsLead')->nullable();
    //         $table->uuid('RelatedProspectId')->nullable();
    //         $table->text('SourceReferrer')->nullable();
    //         $table->string('NotableEvent')->nullable();
    //         $table->timestamp('NotableEventdate')->nullable();
    //         $table->json('raw')->nullable();
    //         $table->timestamp('LastVisitDate')->nullable();
    //         $table->string('RelatedLandingPageId')->nullable();
    //         $table->string('FirstLandingPageSubmissionId')->nullable();
    //         $table->timestamp('FirstLandingPageSubmissionDate')->nullable();
    //         $table->string('ProspectActivityName_Max')->nullable();
    //         $table->timestamp('ProspectActivityDate_Max')->nullable();
    //         $table->timestamp('ProspectActivityDate_Min')->nullable();
    //         $table->string('Web_Referrer')->nullable();
    //         $table->string('Web_RefKeyword')->nullable();
    //         $table->timestamp('LeadLastModifiedOn')->nullable();
    //         $table->string('ConversionReferrerURL')->nullable();
    //         $table->string('SourceReferrerURL')->nullable();
    //         $table->string('SourceIPAddress')->nullable();
    //         $table->decimal('Latitude', 10, 7)->nullable();
    //         $table->decimal('Longitude', 10, 7)->nullable();
    //         $table->string('FirstName')->nullable();
    //         $table->string('LastName')->nullable();
    //         $table->string('EmailAddress')->nullable();
    //         $table->string('Phone')->nullable();
    //         $table->string('Company')->nullable();
    //         $table->string('Source')->nullable();
    //         $table->string('Mobile')->nullable();
    //         $table->string('SourceCampaign')->nullable();
    //         $table->string('Website')->nullable();
    //         $table->boolean('DoNotEmail')->nullable();
    //         $table->boolean('DoNotTrack')->nullable();
    //         $table->boolean('DoNotSMS')->nullable();
    //         $table->boolean('DoNotCall')->nullable();
    //         $table->string('SourceMedium')->nullable();
    //         $table->string('JobTitle')->nullable();
    //         $table->text('SourceContent')->nullable();
    //         $table->text('Notes')->nullable();
    //         $table->integer('Score')->nullable();
    //         $table->integer('EngagementScore')->nullable();
    //         $table->decimal('Revenue', 15, 2)->nullable();
    //         $table->string('ProspectStage')->nullable();
    //         $table->string('QualityScore01')->nullable();
    //         $table->uuid('OwnerId')->nullable();
    //         $table->uuid('CreatedBy')->nullable();
    //         $table->string('CreatedByName')->nullable();
    //         $table->timestamp('CreatedOn')->nullable();
    //         $table->timestamp('LeadConversionDate')->nullable();
    //         $table->uuid('ModifiedBy')->nullable();
    //         $table->string('ModifiedByName')->nullable();
    //         $table->timestamp('ModifiedOn')->nullable();
    //         $table->string('TimeZone')->nullable();
    //         $table->integer('TotalVisits')->nullable();
    //         $table->integer('PageViewsPerVisit')->nullable();
    //         $table->integer('AvgTimePerVisit')->nullable();
    //         $table->string('mx_Street1')->nullable();
    //         $table->string('mx_Street2')->nullable();
    //         $table->string('mx_City')->nullable();
    //         $table->string('mx_Country')->nullable();
    //         $table->string('mx_Zip')->nullable();
    //         $table->string('OwnerIdName')->nullable();
    //         $table->string('OwnerIdEmailAddress')->nullable();
    //         $table->string('Origin')->nullable();
    //         $table->json('MailingPreferences')->nullable();
    //         $table->json('Groups')->nullable();
    //         // $table->string('TwitterId')->nullable();
    //         // $table->string('PhotoUrl')->nullable();
    //         // $table->string('FacebookId')->nullable();
    //         // $table->string('LinkedInId')->nullable();
    //         // $table->string('SkypeId')->nullable();
    //         $table->string('GTalkId')->nullable();
    //         $table->string('GooglePlusId')->nullable();
    //         $table->string('CurrentOptInStatus')->nullable();
    //         $table->timestamp('OptInDate')->nullable();
    //         $table->text('OptInDetails')->nullable();
    //         $table->timestamp('LastOptInEmailSentDate')->nullable();
    //         $table->integer('LeadAge')->nullable();
    //         $table->string('mx_Course_Interested')->nullable();
    //         $table->string('mx_Graduation')->nullable();
    //         $table->string('mx_Gender')->nullable();
    //         $table->date('mx_Date_of_Birth')->nullable();
    //         $table->string('mx_Post_Graduation_Or_Other_Certification')->nullable();
    //         $table->string('mx_Work_Experience')->nullable();
    //         $table->timestamp('mx_Joined_Date')->nullable();
    //         $table->string('mx_Preferred_Language')->nullable();
    //         $table->text('mx_About_me')->nullable();
    //         $table->string('mx_Education_Completed')->nullable();
    //         $table->string('mx_Twitter_Link')->nullable();
    //         $table->string('mx_Facebook_Link')->nullable();
    //         $table->string('mx_LinkedIn_Link')->nullable();
    //         $table->string('mx_Card_type')->nullable();
    //         $table->string('mx_Last_4_digit_of_card')->nullable();
    //         $table->string('mx_Name_on_Card')->nullable();
    //         $table->string('mx_Transaction_ID')->nullable();
    //         $table->string('mx_Bank_Name')->nullable();
    //         $table->decimal('mx_Total_paid', 15, 2)->nullable();
    //         $table->timestamp('mx_Follow_Up_Date_Time')->nullable();
    //         $table->string('mx_State')->nullable();
    //         $table->string('mx_Year_of_Birth')->nullable();
    //         $table->string('mx_Brochure')->nullable();
    //         $table->string('mx_otp')->nullable();
    //         $table->string('mx_Ad_Name')->nullable();
    //         $table->string('mx_campaign_Id')->nullable();
    //         $table->string('mx_Adset_Name')->nullable();
    //         $table->string('mx_UTM_Source')->nullable();
    //         $table->string('mx_UTM_Term')->nullable();
    //         $table->string('mx_Facebook_Form')->nullable();
    //         $table->string('mx_Facebook_Page')->nullable();
    //         $table->string('mx_Status')->nullable();
    //         $table->string('mx_Outcome')->nullable();
    //         $table->string('mx_Lead_Course')->nullable();
    //         $table->string('mx_GCLID')->nullable();
    //         $table->string('mx_AD_Network')->nullable();
    //         $table->string('mx_AD_Campaign_ID')->nullable();
    //         $table->string('mx_AD_Campaign_Name')->nullable();
    //         $table->string('mx_Keyword')->nullable();
    //         $table->string('mx_Click_Type')->nullable();
    //         $table->string('mx_Device')->nullable();
    //         $table->timestamp('mx_AD_Click_Date')->nullable();
    //         $table->string('mx_AD_Group_Name')->nullable();
    //         $table->string('mx_Search_Partner_Network')->nullable();
    //         $table->string('mx_Keyword_Match_Type')->nullable();
    //         $table->string('mx_lp_source')->nullable();
    //         $table->string('mx_lp_campaign')->nullable();
    //         $table->string('mx_Age')->nullable();
    //         $table->string('mx_Application_Status')->nullable();
    //         $table->string('mx_Alternate_Email')->nullable();
    //         $table->integer('mx_Resubmission_Counter')->nullable();
    //         $table->string('mx_Device_Type')->nullable();
    //         $table->string('mx_Device_Name')->nullable();
    //         $table->string('mx_SourceTerm')->nullable();
    //         $table->string('mx_BTTR')->nullable();
    //         $table->string('mx_Trigger')->nullable();
    //         $table->integer('mx_Total_Calls_in_Lead')->nullable();
    //         $table->integer('mx_Total_Answered_Calls')->nullable();
    //         $table->timestamp('mx_Last_Follow_Up_Date')->nullable();
    //         $table->string('mx_Pre_Qualified_Leads')->nullable();
    //         $table->text('mx_Activity_Notes')->nullable();
    //         $table->string('mx_mail_trigger')->nullable();
    //         $table->text('mx_Customer_Query')->nullable();
    //         $table->string('mx_Lead_Sub_Status')->nullable();
    //         $table->string('mx_utm_medium')->nullable();
    //         $table->string('mx_Latest_Source_Campaign')->nullable();
    //         $table->string('mx_Latest_Source_Medium')->nullable();
    //         $table->string('mx_Re_Lead_Capture')->nullable();
    //         $table->string('mx_Current_Lead_Source')->nullable();
    //         $table->string('mx_Decision_Maker')->nullable();
    //         $table->text('mx_Short_Notes')->nullable();
    //         $table->string('mx_Sub_Status')->nullable();
    //         $table->string('mx_Job_status')->nullable();
    //         $table->string('mx_Primary_reason_for_course')->nullable();
    //         $table->string('mx_Whatsapp_action')->nullable();
    //         $table->text('mx_Lead_URL')->nullable();
    //         $table->string('mx_Portal_IsPortalUser')->nullable();
    //         $table->string('mx_utm_creative_id')->nullable();
    //         $table->string('mx_FB_LeadGen_ID')->nullable();
    //         $table->string('mx_Program_Type')->nullable();
    //         $table->string('mx_Lead_Type')->nullable();
    //         $table->string('mx_School')->nullable();
    //         $table->string('mx_mx_utm_marketing')->nullable();
    //         $table->string('mx_Student_Profile')->nullable();
    //         $table->string('mx_Looking_For')->nullable();
    //         $table->string('mx_Quality_Lead')->nullable();
    //         $table->string('mx_Source_Category')->nullable();
    //         $table->string('mx_Courses_Category')->nullable();
    //         $table->json('mx_Document')->nullable();
    //         $table->json('mx_Documents')->nullable();
    //         $table->json('mx_Registration_Document')->nullable();
    //         $table->string('mx_Created_Source_Campaign')->nullable();
    //         $table->string('mx_gradCollege')->nullable();
    //         $table->string('mx_gradUniversity')->nullable();
    //         $table->string('mx_gradYear')->nullable();
    //         $table->string('mx_gradMarks')->nullable();
    //         $table->string('mx_PassportNum')->nullable();
    //         $table->string('mx_currWork')->nullable();
    //         $table->string('mx_workExp')->nullable();
    //         $table->string('mx_Software_Used')->nullable();
    //         $table->string('mx_Education_in_Interior_Design')->nullable();
    //         $table->timestamp('mx_Interested_on_date')->nullable();
    //         $table->string('mx_Education')->nullable();
    //         $table->string('mx_Pursue_Online_Course')->nullable();
    //         $table->string('mx_SSC_Aggregate_Marks')->nullable();
    //         $table->string('mx_HSC_Diploma_Aggregate_Marks')->nullable();
    //         $table->string('mx_VA_RC_Scaled_Percentile')->nullable();
    //         $table->string('mx_DI_LR_Scaled_Percentile')->nullable();
    //         $table->string('mx_Total_Percentile')->nullable();
    //         $table->string('mx_Bachelor_Degree_Marks')->nullable();
    //         $table->string('mx_Preferred_Payment')->nullable();
    //         $table->timestamp('mx_Enrolled_At')->nullable();
    //         $table->string('mx_comfortable_pursuing_this_course_in_English')->nullable();
    //         $table->string('mx_Do_u_have_a_minimum_of_8GB_RAM_Computer_Laptop')->nullable();
    //         $table->text('mx_What_aspects_of_music_prod_are_you_most_interested')->nullable();
    //         $table->string('mx_Have_you_encountered_any_hurdles_or_challenges_in')->nullable();
    //         $table->string('mx_What_specifically_about')->nullable();
    //         $table->string('mx_Have_you_written_any_scripts_or_stories_so_far')->nullable();
    //         $table->string('mx_What_is_your_motivation_to_enroll_in')->nullable();
    //         $table->string('mx_What_aspect_of')->nullable();
    //         $table->timestamp('mx_First_lead_Date')->nullable();
    //         $table->timestamp('mx_Re_Submission_Date')->nullable();
    //         $table->integer('mx_Miss_Call_Counter')->nullable();
    //         $table->string('mx_Facebook_Re_Capture')->nullable();
    //         $table->timestamp('mx_FB_Recapture_Date')->nullable();
    //         $table->string('mx_Level_of_interest')->nullable();
    //         $table->string('mx_Average_Time')->nullable();
    //         $table->string('mx_Verified_Tech')->nullable();
    //         $table->timestamp('mx_Conversion_Date')->nullable();
    //         $table->string('mx_Comfortable_with_course_fee')->nullable();
    //         $table->string('mx_Comfortable_with_course_hours')->nullable();
    //         $table->integer('mx_Total_Messages')->nullable();
    //         $table->integer('mx_Messages_Received')->nullable();
    //         $table->integer('mx_Messages_Sent')->nullable();
    //         $table->integer('mx_Follow_ups')->nullable();
    //         $table->integer('mx_Messages_you_got')->nullable();
    //         $table->integer('mx_Messages_you_sent')->nullable();
    //         $table->text('mx_Talking_Points_for_Next_Conversation')->nullable();
    //         $table->decimal('mx_Salary', 15, 2)->nullable();



    //         $table->timestamps();
    //     });
    // }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('lead_search_leads');
    }
};
